[project]
name = "pacman"
version = "0.1.0"
description = "Pac-Man implementation in Python"
readme = "README.md"

authors = [
    { name = "borabi" },
    { name = "hqasqas" }
]

requires-python = ">=3.10"

dependencies = [
    "pygame>=2.6.1",
    "mazegenerator",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.uv.sources]
mazegenerator = { path = "libs/mazegenerator-2.1.0-py3-none-any.whl" }

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=1.11.0",
    "pyinstaller>=6.22.2",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]
